title: Jekyll theme SAIFAS IT
author:
  name: SAIFAS
copyright: © SAIFAS
version: 0.1.6
lang: en_US
author: SAIFAS
email: jekyll@saifas.info
about: Jekyll theme SAIFAS IT

gems:

sass:
  sass_dir: /_sass/

assets_root_path: /assets/
assets_styles_path: /assets/sass/styles.css